% structure.pl — Tier 2 empirical facts, scanned from the codebase by the agent.
% Same EAV shape as axioms; the loader tags these as `observed`. Each fact should
% have a matching entry in provenance.pl.
%
% entity('/abc', endpoint).
% prop('/abc', requires_auth, true).
% rel(c42, depends_on, lib_theme).
entity(mealRecommendation,service).
entity(mealRecommendationModel,service).
entity(mealRecommendationAi,service).
entity(mealRecommendationEval,service).
entity(mealFeatures,service).
entity(mealItemIdentity,service).
entity(officeRecommenderSettings,service).
entity(userPreferences,service).
entity(db,module).
entity(lib_types,module).
entity(routeUtils,module).
entity(recommenderAdmin,route).
rel(mealRecommendation,depends_on,db).
rel(mealRecommendation,depends_on,mealRecommendationAi).
rel(mealRecommendation,depends_on,mealFeatures).
rel(mealRecommendation,depends_on,mealRecommendationModel).
rel(mealRecommendation,depends_on,mealItemIdentity).
rel(mealRecommendation,depends_on,userPreferences).
rel(mealRecommendation,depends_on,lib_types).
rel(recommenderAdmin,depends_on,routeUtils).
rel(recommenderAdmin,depends_on,authIdentity).
rel(recommenderAdmin,depends_on,mealRecommendationEval).
rel(recommenderAdmin,depends_on,officeRecommenderSettings).
rel(recommenderAdmin,depends_on,mealRecommendationModel).
rel(recommenderAdmin,depends_on,lib_types).
entity('POST:/api/menus',endpoint).
prop('POST:/api/menus',method,post).
prop('POST:/api/menus',path,'/api/menus').
prop('POST:/api/menus',mutates_state,true).
entity('POST:/api/menus/import',endpoint).
prop('POST:/api/menus/import',method,post).
prop('POST:/api/menus/import',path,'/api/menus/import').
prop('POST:/api/menus/import',mutates_state,true).
entity('PUT:/api/menus/:id',endpoint).
prop('PUT:/api/menus/:id',method,put).
prop('PUT:/api/menus/:id',path,'/api/menus/:id').
prop('PUT:/api/menus/:id',mutates_state,true).
entity('DELETE:/api/menus/:id',endpoint).
prop('DELETE:/api/menus/:id',method,delete).
prop('DELETE:/api/menus/:id',path,'/api/menus/:id').
prop('DELETE:/api/menus/:id',mutates_state,true).
entity('POST:/api/menus/:menuId/items',endpoint).
prop('POST:/api/menus/:menuId/items',method,post).
prop('POST:/api/menus/:menuId/items',path,'/api/menus/:menuId/items').
prop('POST:/api/menus/:menuId/items',mutates_state,true).
entity('PUT:/api/menus/:menuId/items/:id',endpoint).
prop('PUT:/api/menus/:menuId/items/:id',method,put).
prop('PUT:/api/menus/:menuId/items/:id',path,'/api/menus/:menuId/items/:id').
prop('PUT:/api/menus/:menuId/items/:id',mutates_state,true).
entity('DELETE:/api/menus/:menuId/items/:id',endpoint).
prop('DELETE:/api/menus/:menuId/items/:id',method,delete).
prop('DELETE:/api/menus/:menuId/items/:id',path,'/api/menus/:menuId/items/:id').
prop('DELETE:/api/menus/:menuId/items/:id',mutates_state,true).
entity('GET:/api/menus',endpoint).
prop('GET:/api/menus',method,get).
prop('GET:/api/menus',path,'/api/menus').
prop('GET:/api/menus',mutates_state,false).
entity('GET:/api/food-selections/active',endpoint).
prop('GET:/api/food-selections/active',method,get).
prop('GET:/api/food-selections/active',path,'/api/food-selections/active').
prop('GET:/api/food-selections/active',mutates_state,false).
entity('GET:/api/food-selections/history',endpoint).
prop('GET:/api/food-selections/history',method,get).
prop('GET:/api/food-selections/history',path,'/api/food-selections/history').
prop('GET:/api/food-selections/history',mutates_state,false).
entity('GET:/api/food-selections/:id/fallback-candidates',endpoint).
prop('GET:/api/food-selections/:id/fallback-candidates',method,get).
prop('GET:/api/food-selections/:id/fallback-candidates',path,'/api/food-selections/:id/fallback-candidates').
prop('GET:/api/food-selections/:id/fallback-candidates',mutates_state,false).
entity('GET:/api/polls/active',endpoint).
prop('GET:/api/polls/active',method,get).
prop('GET:/api/polls/active',path,'/api/polls/active').
prop('GET:/api/polls/active',mutates_state,false).
entity('GET:/api/polls/:id',endpoint).
prop('GET:/api/polls/:id',method,get).
prop('GET:/api/polls/:id',path,'/api/polls/:id').
prop('GET:/api/polls/:id',mutates_state,false).
entity('GET:/api/shopping-list',endpoint).
prop('GET:/api/shopping-list',method,get).
prop('GET:/api/shopping-list',path,'/api/shopping-list').
prop('GET:/api/shopping-list',mutates_state,false).
prop('POST:/api/menus',requires_auth,true).
prop('POST:/api/menus/import',requires_auth,true).
prop('PUT:/api/menus/:id',requires_auth,true).
prop('DELETE:/api/menus/:id',requires_auth,true).
prop('POST:/api/menus/:menuId/items',requires_auth,true).
prop('PUT:/api/menus/:menuId/items/:id',requires_auth,true).
prop('DELETE:/api/menus/:menuId/items/:id',requires_auth,true).
prop('GET:/api/menus',requires_auth,true).
prop('GET:/api/food-selections/active',requires_auth,true).
prop('GET:/api/food-selections/history',requires_auth,true).
prop('GET:/api/food-selections/:id/fallback-candidates',requires_auth,true).
prop('GET:/api/polls/active',requires_auth,true).
prop('GET:/api/polls/:id',requires_auth,true).
prop('GET:/api/shopping-list',requires_auth,true).
entity(faim,tool).
entity(faim,tool).
prop(faim,version,'0.4.0').
entity(authAccess,service).
entity(authAudit,service).
entity(authAvatar,service).
entity(authSession,service).
entity(dbConnectivity,service).
entity(displayName,service).
entity(entraOidc,service).
entity(foodSelection,service).
entity(localAuth,service).
entity(localLoginProtection,service).
entity(mealAnticipatedLikes,service).
entity(mealRecommendationExplore,service).
entity(mealRecommendationModelXlearn,service).
entity(mealRecommendationPreVote,service).
entity(menu,service).
entity(notificationEmail,service).
entity(officeContext,service).
entity(officeLocation,service).
entity(officePollSchedule,service).
entity(poll,service).
entity(seededRng,service).
entity(shoppingList,service).
entity(userMenuDefaults,service).
entity(sse,module).
entity(auth_route,route).
entity(authIdentity,route).
entity(foodSelections_route,route).
entity(menus_route,route).
entity(polls_route,route).
entity(shoppingList_route,route).
entity(userPreferences_route,route).
rel(entraOidc,depends_on,routeUtils).
rel(localLoginProtection,depends_on,routeUtils).
rel(displayName,depends_on,routeUtils).
rel(dbConnectivity,depends_on,db).
rel(localAuth,depends_on,db).
rel(localAuth,depends_on,routeUtils).
rel(foodSelection,depends_on,db).
rel(foodSelection,depends_on,sse).
rel(foodSelection,depends_on,lib_types).
rel(foodSelection,depends_on,notificationEmail).
rel(foodSelection,depends_on,officeLocation).
rel(authAudit,depends_on,db).
rel(authAudit,depends_on,localAuth).
rel(authAccess,depends_on,db).
rel(authAccess,depends_on,routeUtils).
rel(authAccess,depends_on,localAuth).
rel(authAccess,depends_on,notificationEmail).
rel(authAccess,depends_on,officeLocation).
rel(authAccess,depends_on,displayName).
rel(authAccess,depends_on,authAudit).
rel(mealItemIdentity,depends_on,db).
rel(mealItemIdentity,depends_on,routeUtils).
rel(mealRecommendation,depends_on,db).
rel(mealRecommendation,depends_on,routeUtils).
rel(mealRecommendation,depends_on,lib_types).
rel(mealRecommendation,depends_on,mealRecommendationAi).
rel(mealRecommendation,depends_on,mealFeatures).
rel(mealRecommendation,depends_on,mealRecommendationModel).
rel(mealRecommendation,depends_on,mealItemIdentity).
rel(mealRecommendation,depends_on,userPreferences).
rel(mealRecommendationAi,depends_on,lib_types).
rel(mealRecommendationEval,depends_on,db).
rel(mealRecommendationEval,depends_on,routeUtils).
rel(mealRecommendationEval,depends_on,mealFeatures).
rel(mealRecommendationEval,depends_on,mealRecommendationModel).
rel(mealRecommendationEval,depends_on,lib_types).
rel(mealRecommendationExplore,depends_on,db).
rel(mealRecommendationExplore,depends_on,lib_types).
rel(mealRecommendationExplore,depends_on,seededRng).
rel(mealRecommendationExplore,depends_on,mealFeatures).
rel(mealRecommendationExplore,depends_on,mealRecommendation).
rel(mealRecommendationExplore,depends_on,userPreferences).
rel(mealRecommendationModel,depends_on,db).
rel(mealRecommendationModel,depends_on,routeUtils).
rel(mealRecommendationModel,depends_on,seededRng).
rel(mealRecommendationModel,depends_on,mealFeatures).
rel(mealRecommendationModel,depends_on,mealItemIdentity).
rel(mealRecommendationModel,depends_on,lib_types).
rel(mealRecommendationModelXlearn,depends_on,mealRecommendationModel).
rel(mealRecommendationPreVote,depends_on,db).
rel(mealRecommendationPreVote,depends_on,routeUtils).
rel(mealRecommendationPreVote,depends_on,lib_types).
rel(mealRecommendationPreVote,depends_on,mealRecommendation).
rel(mealRecommendationPreVote,depends_on,mealFeatures).
rel(mealRecommendationPreVote,depends_on,mealRecommendationModel).
rel(mealRecommendationPreVote,depends_on,mealItemIdentity).
rel(mealAnticipatedLikes,depends_on,db).
rel(mealAnticipatedLikes,depends_on,routeUtils).
rel(mealAnticipatedLikes,depends_on,mealFeatures).
rel(mealAnticipatedLikes,depends_on,mealItemIdentity).
rel(mealAnticipatedLikes,depends_on,lib_types).
rel(mealFeatures,depends_on,db).
rel(menu,depends_on,db).
rel(menu,depends_on,sse).
rel(menu,depends_on,officeLocation).
rel(menu,depends_on,mealItemIdentity).
rel(menu,depends_on,mealFeatures).
rel(menu,depends_on,mealRecommendationAi).
rel(menu,depends_on,lib_types).
rel(officeLocation,depends_on,db).
rel(officeLocation,depends_on,routeUtils).
rel(officeLocation,depends_on,lib_types).
rel(officeContext,depends_on,authSession).
rel(officeContext,depends_on,authAccess).
rel(officeContext,depends_on,officeLocation).
rel(officeContext,depends_on,routeUtils).
rel(officePollSchedule,depends_on,db).
rel(officePollSchedule,depends_on,officeLocation).
rel(officePollSchedule,depends_on,lib_types).
rel(officeRecommenderSettings,depends_on,db).
rel(officeRecommenderSettings,depends_on,routeUtils).
rel(officeRecommenderSettings,depends_on,lib_types).
rel(officeRecommenderSettings,depends_on,mealRecommendationModel).
rel(poll,depends_on,db).
rel(poll,depends_on,sse).
rel(poll,depends_on,lib_types).
rel(poll,depends_on,authAccess).
rel(poll,depends_on,notificationEmail).
rel(poll,depends_on,officeLocation).
rel(shoppingList,depends_on,db).
rel(shoppingList,depends_on,sse).
rel(shoppingList,depends_on,lib_types).
rel(shoppingList,depends_on,officeLocation).
rel(userPreferences,depends_on,db).
rel(userPreferences,depends_on,lib_types).
rel(userMenuDefaults,depends_on,db).
rel(userMenuDefaults,depends_on,lib_types).
rel(sse,depends_on,db).
rel(sse,depends_on,lib_types).
rel(sse,depends_on,officeLocation).
rel(auth_route,depends_on,lib_types).
rel(auth_route,depends_on,routeUtils).
rel(auth_route,depends_on,authSession).
rel(auth_route,depends_on,localAuth).
rel(auth_route,depends_on,entraOidc).
rel(auth_route,depends_on,localLoginProtection).
rel(auth_route,depends_on,authAccess).
rel(auth_route,depends_on,sse).
rel(auth_route,depends_on,officeLocation).
rel(auth_route,depends_on,authAudit).
rel(auth_route,depends_on,authAvatar).
rel(auth_route,depends_on,dbConnectivity).
rel(authIdentity,depends_on,authSession).
rel(authIdentity,depends_on,authAccess).
rel(authIdentity,depends_on,localAuth).
rel(authIdentity,depends_on,routeUtils).
rel(recommenderAdmin,depends_on,routeUtils).
rel(recommenderAdmin,depends_on,authIdentity).
rel(recommenderAdmin,depends_on,mealRecommendationEval).
rel(recommenderAdmin,depends_on,officeRecommenderSettings).
rel(recommenderAdmin,depends_on,mealRecommendationModel).
rel(recommenderAdmin,depends_on,lib_types).
rel(userPreferences_route,depends_on,routeUtils).
rel(userPreferences_route,depends_on,userPreferences).
rel(userPreferences_route,depends_on,userMenuDefaults).
rel(userPreferences_route,depends_on,authIdentity).
rel(userPreferences_route,depends_on,lib_types).
rel(menus_route,depends_on,menu).
rel(menus_route,depends_on,routeUtils).
rel(menus_route,depends_on,officeContext).
rel(menus_route,depends_on,authIdentity).
rel(menus_route,depends_on,lib_types).
rel(polls_route,depends_on,poll).
rel(polls_route,depends_on,db).
rel(polls_route,depends_on,routeUtils).
rel(polls_route,depends_on,authSession).
rel(polls_route,depends_on,authAccess).
rel(polls_route,depends_on,officeContext).
rel(polls_route,depends_on,authIdentity).
rel(polls_route,depends_on,lib_types).
rel(shoppingList_route,depends_on,shoppingList).
rel(shoppingList_route,depends_on,routeUtils).
rel(shoppingList_route,depends_on,officeContext).
rel(shoppingList_route,depends_on,authIdentity).
rel(shoppingList_route,depends_on,lib_types).
rel(foodSelections_route,depends_on,foodSelection).
rel(foodSelections_route,depends_on,poll).
rel(foodSelections_route,depends_on,mealRecommendation).
rel(foodSelections_route,depends_on,mealRecommendationExplore).
rel(foodSelections_route,depends_on,mealRecommendationPreVote).
rel(foodSelections_route,depends_on,mealAnticipatedLikes).
rel(foodSelections_route,depends_on,db).
rel(foodSelections_route,depends_on,routeUtils).
rel(foodSelections_route,depends_on,authAccess).
rel(foodSelections_route,depends_on,officeContext).
rel(foodSelections_route,depends_on,authIdentity).
rel(foodSelections_route,depends_on,lib_types).
entity(pollCreation,service).
rel(pollCreation,depends_on,db).
rel(pollCreation,depends_on,officeLocation).
rel(pollCreation,depends_on,lib_types).
rel(poll,depends_on,pollCreation).
rel(officePollSchedule,depends_on,pollCreation).
rel(sse,depends_on,pollCreation).
rel(officePollSchedule,depends_on,pollCreation).
rel(poll,depends_on,pollCreation).
rel(poll,depends_on,officeLocation).
rel(sse,depends_on,pollCreation).
