% structure.pl — Tier 2 empirical facts, scanned from the codebase by the agent.
% Same EAV shape as axioms; the loader tags these as `observed`. Each fact should
% have a matching entry in provenance.pl.
%
% entity('/abc', endpoint).
% prop('/abc', requires_auth, true).
% rel(c42, depends_on, lib_theme).
rel(mealRecommendation,depends_on,db).
rel(mealRecommendation,depends_on,mealRecommendationAi).
rel(mealRecommendation,depends_on,mealFeatures).
rel(mealRecommendation,depends_on,mealRecommendationModel).
rel(mealRecommendation,depends_on,mealItemIdentity).
rel(mealRecommendation,depends_on,userPreferences).
rel(mealRecommendation,depends_on,lib_types).
rel(recommenderAdmin,depends_on,routeUtils).
rel(recommenderAdmin,depends_on,authIdentity).
rel(recommenderAdmin,depends_on,mealRecommendationEval).
rel(recommenderAdmin,depends_on,officeRecommenderSettings).
rel(recommenderAdmin,depends_on,mealRecommendationModel).
rel(recommenderAdmin,depends_on,lib_types).
entity(faim,tool).
entity(faim,tool).
entity(authAccess,service).
entity(authAudit,service).
entity(authAvatar,service).
entity(authSession,service).
entity(dbConnectivity,service).
entity(displayName,service).
entity(entraOidc,service).
entity(foodSelection,service).
entity(localAuth,service).
entity(localLoginProtection,service).
entity(mealAnticipatedLikes,service).
entity(mealRecommendationExplore,service).
entity(mealRecommendationModelXlearn,service).
entity(mealRecommendationPreVote,service).
entity(menu,service).
entity(notificationEmail,service).
entity(officeContext,service).
entity(officeLocation,service).
entity(officePollSchedule,service).
entity(poll,service).
entity(seededRng,service).
entity(shoppingList,service).
entity(userMenuDefaults,service).
entity(sse,module).
entity(auth_route,route).
entity(authIdentity,route).
entity(foodSelections_route,route).
entity(menus_route,route).
entity(polls_route,route).
entity(shoppingList_route,route).
entity(userPreferences_route,route).
rel(entraOidc,depends_on,routeUtils).
rel(localLoginProtection,depends_on,routeUtils).
rel(displayName,depends_on,routeUtils).
rel(dbConnectivity,depends_on,db).
rel(localAuth,depends_on,db).
rel(localAuth,depends_on,routeUtils).
rel(foodSelection,depends_on,db).
rel(foodSelection,depends_on,sse).
rel(foodSelection,depends_on,lib_types).
rel(foodSelection,depends_on,notificationEmail).
rel(foodSelection,depends_on,officeLocation).
rel(authAudit,depends_on,db).
rel(authAudit,depends_on,localAuth).
rel(authAccess,depends_on,db).
rel(authAccess,depends_on,routeUtils).
rel(authAccess,depends_on,localAuth).
rel(authAccess,depends_on,notificationEmail).
rel(authAccess,depends_on,officeLocation).
rel(authAccess,depends_on,displayName).
rel(authAccess,depends_on,authAudit).
rel(mealItemIdentity,depends_on,db).
rel(mealItemIdentity,depends_on,routeUtils).
rel(mealRecommendation,depends_on,db).
rel(mealRecommendation,depends_on,routeUtils).
rel(mealRecommendation,depends_on,lib_types).
rel(mealRecommendation,depends_on,mealRecommendationAi).
rel(mealRecommendation,depends_on,mealFeatures).
rel(mealRecommendation,depends_on,mealRecommendationModel).
rel(mealRecommendation,depends_on,mealItemIdentity).
rel(mealRecommendation,depends_on,userPreferences).
rel(mealRecommendationAi,depends_on,lib_types).
rel(mealRecommendationEval,depends_on,db).
rel(mealRecommendationEval,depends_on,routeUtils).
rel(mealRecommendationEval,depends_on,mealFeatures).
rel(mealRecommendationEval,depends_on,mealRecommendationModel).
rel(mealRecommendationEval,depends_on,lib_types).
rel(mealRecommendationExplore,depends_on,db).
rel(mealRecommendationExplore,depends_on,lib_types).
rel(mealRecommendationExplore,depends_on,seededRng).
rel(mealRecommendationExplore,depends_on,mealFeatures).
rel(mealRecommendationExplore,depends_on,mealRecommendation).
rel(mealRecommendationExplore,depends_on,userPreferences).
rel(mealRecommendationModel,depends_on,db).
rel(mealRecommendationModel,depends_on,routeUtils).
rel(mealRecommendationModel,depends_on,seededRng).
rel(mealRecommendationModel,depends_on,mealFeatures).
rel(mealRecommendationModel,depends_on,mealItemIdentity).
rel(mealRecommendationModel,depends_on,lib_types).
rel(mealRecommendationModelXlearn,depends_on,mealRecommendationModel).
rel(mealRecommendationPreVote,depends_on,db).
rel(mealRecommendationPreVote,depends_on,routeUtils).
rel(mealRecommendationPreVote,depends_on,lib_types).
rel(mealRecommendationPreVote,depends_on,mealRecommendation).
rel(mealRecommendationPreVote,depends_on,mealFeatures).
rel(mealRecommendationPreVote,depends_on,mealRecommendationModel).
rel(mealRecommendationPreVote,depends_on,mealItemIdentity).
rel(mealAnticipatedLikes,depends_on,db).
rel(mealAnticipatedLikes,depends_on,routeUtils).
rel(mealAnticipatedLikes,depends_on,mealFeatures).
rel(mealAnticipatedLikes,depends_on,mealItemIdentity).
rel(mealAnticipatedLikes,depends_on,lib_types).
rel(mealFeatures,depends_on,db).
rel(menu,depends_on,db).
rel(menu,depends_on,sse).
rel(menu,depends_on,officeLocation).
rel(menu,depends_on,mealItemIdentity).
rel(menu,depends_on,mealFeatures).
rel(menu,depends_on,mealRecommendationAi).
rel(menu,depends_on,lib_types).
rel(officeLocation,depends_on,db).
rel(officeLocation,depends_on,routeUtils).
rel(officeLocation,depends_on,lib_types).
rel(officeContext,depends_on,authSession).
rel(officeContext,depends_on,authAccess).
rel(officeContext,depends_on,officeLocation).
rel(officeContext,depends_on,routeUtils).
rel(officePollSchedule,depends_on,db).
rel(officePollSchedule,depends_on,officeLocation).
rel(officePollSchedule,depends_on,lib_types).
rel(officeRecommenderSettings,depends_on,db).
rel(officeRecommenderSettings,depends_on,routeUtils).
rel(officeRecommenderSettings,depends_on,lib_types).
rel(officeRecommenderSettings,depends_on,mealRecommendationModel).
rel(poll,depends_on,db).
rel(poll,depends_on,sse).
rel(poll,depends_on,lib_types).
rel(poll,depends_on,authAccess).
rel(poll,depends_on,notificationEmail).
rel(poll,depends_on,officeLocation).
rel(shoppingList,depends_on,db).
rel(shoppingList,depends_on,sse).
rel(shoppingList,depends_on,lib_types).
rel(shoppingList,depends_on,officeLocation).
rel(userPreferences,depends_on,db).
rel(userPreferences,depends_on,lib_types).
rel(userMenuDefaults,depends_on,db).
rel(userMenuDefaults,depends_on,lib_types).
rel(sse,depends_on,db).
rel(sse,depends_on,lib_types).
rel(sse,depends_on,officeLocation).
rel(auth_route,depends_on,lib_types).
rel(auth_route,depends_on,routeUtils).
rel(auth_route,depends_on,authSession).
rel(auth_route,depends_on,localAuth).
rel(auth_route,depends_on,entraOidc).
rel(auth_route,depends_on,localLoginProtection).
rel(auth_route,depends_on,authAccess).
rel(auth_route,depends_on,sse).
rel(auth_route,depends_on,officeLocation).
rel(auth_route,depends_on,authAudit).
rel(auth_route,depends_on,authAvatar).
rel(auth_route,depends_on,dbConnectivity).
rel(authIdentity,depends_on,authSession).
rel(authIdentity,depends_on,authAccess).
rel(authIdentity,depends_on,localAuth).
rel(authIdentity,depends_on,routeUtils).
rel(recommenderAdmin,depends_on,routeUtils).
rel(recommenderAdmin,depends_on,authIdentity).
rel(recommenderAdmin,depends_on,mealRecommendationEval).
rel(recommenderAdmin,depends_on,officeRecommenderSettings).
rel(recommenderAdmin,depends_on,mealRecommendationModel).
rel(recommenderAdmin,depends_on,lib_types).
rel(userPreferences_route,depends_on,routeUtils).
rel(userPreferences_route,depends_on,userPreferences).
rel(userPreferences_route,depends_on,userMenuDefaults).
rel(userPreferences_route,depends_on,authIdentity).
rel(userPreferences_route,depends_on,lib_types).
rel(menus_route,depends_on,menu).
rel(menus_route,depends_on,routeUtils).
rel(menus_route,depends_on,officeContext).
rel(menus_route,depends_on,authIdentity).
rel(menus_route,depends_on,lib_types).
rel(polls_route,depends_on,poll).
rel(polls_route,depends_on,db).
rel(polls_route,depends_on,routeUtils).
rel(polls_route,depends_on,authSession).
rel(polls_route,depends_on,authAccess).
rel(polls_route,depends_on,officeContext).
rel(polls_route,depends_on,authIdentity).
rel(polls_route,depends_on,lib_types).
rel(shoppingList_route,depends_on,shoppingList).
rel(shoppingList_route,depends_on,routeUtils).
rel(shoppingList_route,depends_on,officeContext).
rel(shoppingList_route,depends_on,authIdentity).
rel(shoppingList_route,depends_on,lib_types).
rel(foodSelections_route,depends_on,foodSelection).
rel(foodSelections_route,depends_on,poll).
rel(foodSelections_route,depends_on,mealRecommendation).
rel(foodSelections_route,depends_on,mealRecommendationExplore).
rel(foodSelections_route,depends_on,mealRecommendationPreVote).
rel(foodSelections_route,depends_on,mealAnticipatedLikes).
rel(foodSelections_route,depends_on,db).
rel(foodSelections_route,depends_on,routeUtils).
rel(foodSelections_route,depends_on,authAccess).
rel(foodSelections_route,depends_on,officeContext).
rel(foodSelections_route,depends_on,authIdentity).
rel(foodSelections_route,depends_on,lib_types).
entity(pollCreation,service).
rel(pollCreation,depends_on,db).
rel(pollCreation,depends_on,officeLocation).
rel(pollCreation,depends_on,lib_types).
rel(poll,depends_on,pollCreation).
rel(officePollSchedule,depends_on,pollCreation).
rel(sse,depends_on,pollCreation).
rel(officePollSchedule,depends_on,pollCreation).
rel(poll,depends_on,pollCreation).
rel(poll,depends_on,officeLocation).
rel(sse,depends_on,pollCreation).
prop(faim,version,'0.5.0').
entity('src/lib/types.ts',module).
entity('src/client/config.ts',module).
entity('src/client/api.ts',module).
entity('src/client/auth.ts',module).
entity('src/client/vite-env.d.ts',module).
entity('src/client/context/AppContext.tsx',module).
entity('src/client/hooks/useAppPhase.ts',module).
entity('src/client/hooks/useCountdown.ts',module).
entity('src/client/hooks/useNotificationPreference.ts',module).
entity('src/client/hooks/usePhaseNotifications.ts',module).
entity('src/client/hooks/useSSE.ts',module).
entity('src/client/lib/cn.ts',module).
entity('src/client/utils/dashboard.ts',module).
entity('src/client/utils/orderCopy.ts',module).
entity('src/lib/ingredientVocabulary.ts',module).
entity('src/server/buildInfo.ts',module).
entity('src/server/db.ts',module).
entity('src/server/routes/routeUtils.ts',module).
entity('src/server/services/officeLocation.ts',module).
entity('src/server/services/pollCreation.ts',module).
entity('src/server/sse.ts',module).
entity('src/server/services/mealItemIdentity.ts',module).
entity('src/server/services/mealFeatures.ts',module).
entity('src/server/services/mealRecommendationAi.ts',module).
entity('src/server/services/menu.ts',module).
entity('src/server/services/authSession.ts',module).
entity('src/server/services/localAuth.ts',module).
entity('src/server/services/notificationEmail.ts',module).
entity('src/server/services/displayName.ts',module).
entity('src/server/services/authAudit.ts',module).
entity('src/server/services/authAccess.ts',module).
entity('src/server/services/officeContext.ts',module).
entity('src/server/routes/authIdentity.ts',module).
entity('src/server/routes/menus.ts',module).
entity('src/server/services/foodSelection.ts',module).
entity('src/server/services/poll.ts',module).
entity('src/server/routes/polls.ts',module).
entity('src/server/services/seededRng.ts',module).
entity('src/server/services/mealRecommendationModel.ts',module).
entity('src/server/services/userPreferences.ts',module).
entity('src/server/services/mealRecommendation.ts',module).
entity('src/server/services/mealRecommendationExplore.ts',module).
entity('src/server/services/mealRecommendationPreVote.ts',module).
entity('src/server/services/mealAnticipatedLikes.ts',module).
entity('src/server/routes/foodSelections.ts',module).
entity('src/server/services/mealRecommendationEval.ts',module).
entity('src/server/services/officeRecommenderSettings.ts',module).
entity('src/server/routes/recommenderAdmin.ts',module).
entity('src/server/services/entraOidc.ts',module).
entity('src/server/services/localLoginProtection.ts',module).
entity('src/server/services/authAvatar.ts',module).
entity('src/server/services/dbConnectivity.ts',module).
entity('src/server/routes/auth.ts',module).
entity('src/server/services/userMenuDefaults.ts',module).
entity('src/server/routes/userPreferences.ts',module).
entity('src/server/services/shoppingList.ts',module).
entity('src/server/routes/shoppingList.ts',module).
entity('src/server/services/officePollSchedule.ts',module).
entity('src/server/index.ts',module).
entity('src/server/services/mealRecommendationModelXlearn.ts',module).
entity('src/server/types/wlearn-xlearn.d.ts',module).
entity('src/client/context/AdminOfficeContext.tsx',module).
entity('src/client/context/ThemeContext.tsx',module).
entity('src/client/components/ui/IconButton.tsx',module).
entity('src/client/components/ui/Menu.tsx',module).
entity('src/client/components/ThemeToggle.tsx',module).
entity('src/client/components/Header.tsx',module).
entity('src/client/components/ui/Modal.tsx',module).
entity('src/client/components/DatabaseConnectionModal.tsx',module).
entity('src/client/components/OrdersRail.tsx',module).
entity('src/client/components/OrderCopyStatus.tsx',module).
entity('src/client/components/FoodSelectionCompletedView.tsx',module).
entity('src/client/components/MinutesActionDropdown.tsx',module).
entity('src/client/components/PollFinishedView.tsx',module).
entity('src/client/components/NoMenusView.tsx',module).
entity('src/client/components/PollIdleView.tsx',module).
entity('src/client/components/TimerActionHeader.tsx',module).
entity('src/client/components/PollActiveView.tsx',module).
entity('src/client/components/PollTiedView.tsx',module).
entity('src/client/components/MealOnboardingDialog.tsx',module).
entity('src/client/components/FoodSelectionActiveView.tsx',module).
entity('src/client/components/FoodSelectionAbortControl.tsx',module).
entity('src/client/components/FoodSelectionOrderBoard.tsx',module).
entity('src/client/components/FoodSelectionOvertimeView.tsx',module).
entity('src/client/components/FoodSelectionOrderingView.tsx',module).
entity('src/client/components/FoodDeliveryView.tsx',module).
entity('src/client/pages/MainView.tsx',module).
entity('src/client/pages/ManageMenus.tsx',module).
entity('src/client/components/ui/Input.tsx',module).
entity('src/client/components/ui/Button.tsx',module).
entity('src/client/pages/ShoppingList.tsx',module).
entity('src/client/components/ui/Section.tsx',module).
entity('src/client/components/ui/Select.tsx',module).
entity('src/client/pages/Settings.tsx',module).
entity('src/client/components/RecommenderAdminPanel.tsx',module).
entity('src/client/pages/Administration.tsx',module).
entity('src/client/App.tsx',module).
entity('src/client/components/ui/Card.tsx',module).
entity('src/client/components/ui/Panel.tsx',module).
entity('src/client/components/AuthGate.tsx',module).
entity('src/client/main.tsx',module).
entity('src/client/components/ui/Badge.tsx',module).
entity('src/client/components/ui/Divider.tsx',module).
entity('src/client/components/ui/FormField.tsx',module).
entity('src/client/components/ui/Textarea.tsx',module).
entity('tests/client/app-context.test.ts',module).
entity('tests/client/helpers.tsx',module).
entity('tests/client/dashboard-utils.test.ts',module).
entity('tests/client/setup.ts',module).
entity('tests/client/useAppPhase.test.ts',module).
entity('tests/client/usePhaseNotifications.test.ts',module).
entity('tests/client/useSSE.test.ts',module).
entity('tests/e2e/smoke.spec.ts',module).
entity('tests/server/auth-approval-gate.test.ts',module).
entity('tests/server/helpers/db.ts',module).
entity('tests/server/auth-approval-reminder.test.ts',module).
entity('tests/server/auth-audit.test.ts',module).
entity('tests/server/auth-avatar.test.ts',module).
entity('tests/server/auth-hardening.test.ts',module).
entity('tests/server/auth-routes-config.test.ts',module).
entity('tests/server/auth-session.test.ts',module).
entity('tests/server/authenticated-get-routes.test.ts',module).
entity('tests/server/base-path.test.ts',module).
entity('tests/server/db-connectivity.test.ts',module).
entity('tests/server/display-name-identity.test.ts',module).
entity('tests/server/food-order-rating-export.test.ts',module).
entity('tests/server/food-selection-authz.test.ts',module).
entity('tests/server/food-selection-reminder.test.ts',module).
entity('tests/server/food-selection-routes.test.ts',module).
entity('tests/server/food-selection-service.test.ts',module).
entity('tests/server/food-selection-timer.test.ts',module).
entity('tests/server/local-auth.test.ts',module).
entity('tests/server/local-user-management-authz.test.ts',module).
entity('tests/server/meal-anticipated-likes.test.ts',module).
entity('tests/server/meal-features-persistence.test.ts',module).
entity('tests/server/meal-features-tagging.test.ts',module).
entity('tests/server/meal-features.test.ts',module).
entity('tests/server/meal-item-identity.test.ts',module).
entity('tests/server/meal-recommendation-ai.test.ts',module).
entity('tests/server/meal-recommendation-eval.test.ts',module).
entity('tests/server/meal-recommendation-explore.test.ts',module).
entity('tests/server/meal-recommendation-model-xlearn.test.ts',module).
entity('tests/server/meal-recommendation-model.test.ts',module).
entity('tests/server/meal-recommendation-pre-vote.test.ts',module).
entity('tests/server/meal-recommendation-routes.test.ts',module).
entity('tests/server/meal-recommendation-service.test.ts',module).
entity('tests/server/meal-recommendation-transfer.test.ts',module).
entity('tests/server/menu-routes.test.ts',module).
entity('tests/server/menu-service.test.ts',module).
entity('tests/server/notification-email.test.ts',module).
entity('tests/server/office-location-service.test.ts',module).
entity('tests/server/office-poll-schedule.test.ts',module).
entity('tests/server/poll-authz.test.ts',module).
entity('tests/server/poll-routes.test.ts',module).
entity('tests/server/poll-service.test.ts',module).
entity('tests/server/poll-timer.test.ts',module).
entity('tests/server/recommender-admin-routes.test.ts',module).
entity('tests/server/retention-integration.test.ts',module).
entity('tests/server/route-utils.test.ts',module).
entity('tests/server/setup.ts',module).
entity('tests/server/shopping-list-routes.test.ts',module).
entity('tests/server/shopping-list-service.test.ts',module).
entity('tests/server/smoke.test.ts',module).
entity('tests/server/sse-integration.test.ts',module).
entity('tests/server/sse.test.ts',module).
entity('tests/server/user-menu-defaults-service.test.ts',module).
entity('tests/server/user-preferences-routes.test.ts',module).
entity('tests/client/Administration.test.tsx',module).
entity('tests/client/App.test.tsx',module).
entity('tests/client/AuthGate.test.tsx',module).
entity('tests/client/FoodDeliveryView.test.tsx',module).
entity('tests/client/FoodSelectionActiveView.test.tsx',module).
entity('tests/client/FoodSelectionCompletedView.test.tsx',module).
entity('tests/client/FoodSelectionOrderingView.test.tsx',module).
entity('tests/client/FoodSelectionOvertimeView.test.tsx',module).
entity('tests/client/Header.test.tsx',module).
entity('tests/client/MainView.test.tsx',module).
entity('tests/client/ManageMenus.test.tsx',module).
entity('tests/client/MealOnboardingDialog.test.tsx',module).
entity('tests/client/NoMenusView.test.tsx',module).
entity('tests/client/OrdersRail.test.tsx',module).
entity('tests/client/PollActiveView.test.tsx',module).
entity('tests/client/PollFinishedView.test.tsx',module).
entity('tests/client/PollIdleView.test.tsx',module).
entity('tests/client/PollTiedView.test.tsx',module).
entity('tests/client/RecommenderAdminPanel.test.tsx',module).
entity('tests/client/Settings.test.tsx',module).
entity('tests/client/ShoppingList.test.tsx',module).
entity('tests/client/ThemeContext.test.tsx',module).
rel('src/client/api.ts',depends_on,'src/lib/types.ts').
rel('src/client/api.ts',depends_on,'src/client/config.ts').
rel('src/client/auth.ts',depends_on,'src/client/config.ts').
rel('src/client/context/AppContext.tsx',depends_on,'src/lib/types.ts').
rel('src/client/hooks/useAppPhase.ts',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/hooks/useAppPhase.ts',depends_on,'src/lib/types.ts').
rel('src/client/hooks/usePhaseNotifications.ts',depends_on,'src/lib/types.ts').
rel('src/client/hooks/useSSE.ts',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/hooks/useSSE.ts',depends_on,'src/client/hooks/usePhaseNotifications.ts').
rel('src/client/hooks/useSSE.ts',depends_on,'src/lib/types.ts').
rel('src/client/hooks/useSSE.ts',depends_on,'src/client/config.ts').
rel('src/client/utils/dashboard.ts',depends_on,'src/lib/types.ts').
rel('src/client/utils/orderCopy.ts',depends_on,'src/lib/types.ts').
rel('src/server/buildInfo.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/officeLocation.ts',depends_on,'src/server/db.ts').
rel('src/server/services/officeLocation.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/officeLocation.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/pollCreation.ts',depends_on,'src/server/db.ts').
rel('src/server/services/pollCreation.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/pollCreation.ts',depends_on,'src/server/services/officeLocation.ts').
rel('src/server/sse.ts',depends_on,'src/server/db.ts').
rel('src/server/sse.ts',depends_on,'src/lib/types.ts').
rel('src/server/sse.ts',depends_on,'src/server/services/officeLocation.ts').
rel('src/server/sse.ts',depends_on,'src/server/services/pollCreation.ts').
rel('src/server/services/mealItemIdentity.ts',depends_on,'src/server/db.ts').
rel('src/server/services/mealItemIdentity.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/mealFeatures.ts',depends_on,'src/server/db.ts').
rel('src/server/services/mealRecommendationAi.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/menu.ts',depends_on,'src/server/db.ts').
rel('src/server/services/menu.ts',depends_on,'src/server/sse.ts').
rel('src/server/services/menu.ts',depends_on,'src/server/services/officeLocation.ts').
rel('src/server/services/menu.ts',depends_on,'src/server/services/mealItemIdentity.ts').
rel('src/server/services/menu.ts',depends_on,'src/server/services/mealFeatures.ts').
rel('src/server/services/menu.ts',depends_on,'src/server/services/mealRecommendationAi.ts').
rel('src/server/services/menu.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/localAuth.ts',depends_on,'src/server/db.ts').
rel('src/server/services/localAuth.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/displayName.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/authAudit.ts',depends_on,'src/server/db.ts').
rel('src/server/services/authAudit.ts',depends_on,'src/server/services/localAuth.ts').
rel('src/server/services/authAccess.ts',depends_on,'src/server/db.ts').
rel('src/server/services/authAccess.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/authAccess.ts',depends_on,'src/server/services/localAuth.ts').
rel('src/server/services/authAccess.ts',depends_on,'src/server/services/notificationEmail.ts').
rel('src/server/services/authAccess.ts',depends_on,'src/server/services/officeLocation.ts').
rel('src/server/services/authAccess.ts',depends_on,'src/server/services/displayName.ts').
rel('src/server/services/authAccess.ts',depends_on,'src/server/services/authAudit.ts').
rel('src/server/services/authAccess.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/officeContext.ts',depends_on,'src/server/services/authSession.ts').
rel('src/server/services/officeContext.ts',depends_on,'src/server/services/authAccess.ts').
rel('src/server/services/officeContext.ts',depends_on,'src/server/services/officeLocation.ts').
rel('src/server/services/officeContext.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/officeContext.ts',depends_on,'src/lib/types.ts').
rel('src/server/routes/authIdentity.ts',depends_on,'src/server/services/authSession.ts').
rel('src/server/routes/authIdentity.ts',depends_on,'src/server/services/authAccess.ts').
rel('src/server/routes/authIdentity.ts',depends_on,'src/server/services/localAuth.ts').
rel('src/server/routes/authIdentity.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/routes/menus.ts',depends_on,'src/server/services/menu.ts').
rel('src/server/routes/menus.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/routes/menus.ts',depends_on,'src/server/services/officeContext.ts').
rel('src/server/routes/menus.ts',depends_on,'src/server/routes/authIdentity.ts').
rel('src/server/routes/menus.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/foodSelection.ts',depends_on,'src/server/db.ts').
rel('src/server/services/foodSelection.ts',depends_on,'src/server/sse.ts').
rel('src/server/services/foodSelection.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/foodSelection.ts',depends_on,'src/server/services/notificationEmail.ts').
rel('src/server/services/foodSelection.ts',depends_on,'src/server/services/officeLocation.ts').
rel('src/server/services/poll.ts',depends_on,'src/server/db.ts').
rel('src/server/services/poll.ts',depends_on,'src/server/sse.ts').
rel('src/server/services/poll.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/poll.ts',depends_on,'src/server/services/authAccess.ts').
rel('src/server/services/poll.ts',depends_on,'src/server/services/notificationEmail.ts').
rel('src/server/services/poll.ts',depends_on,'src/server/services/officeLocation.ts').
rel('src/server/services/poll.ts',depends_on,'src/server/services/pollCreation.ts').
rel('src/server/services/poll.ts',depends_on,'src/server/services/foodSelection.ts').
rel('src/server/routes/polls.ts',depends_on,'src/server/services/poll.ts').
rel('src/server/routes/polls.ts',depends_on,'src/server/db.ts').
rel('src/server/routes/polls.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/routes/polls.ts',depends_on,'src/server/services/authSession.ts').
rel('src/server/routes/polls.ts',depends_on,'src/server/services/authAccess.ts').
rel('src/server/routes/polls.ts',depends_on,'src/server/services/officeContext.ts').
rel('src/server/routes/polls.ts',depends_on,'src/server/routes/authIdentity.ts').
rel('src/server/routes/polls.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/mealRecommendationModel.ts',depends_on,'src/server/db.ts').
rel('src/server/services/mealRecommendationModel.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/mealRecommendationModel.ts',depends_on,'src/server/services/seededRng.ts').
rel('src/server/services/mealRecommendationModel.ts',depends_on,'src/server/services/mealFeatures.ts').
rel('src/server/services/mealRecommendationModel.ts',depends_on,'src/server/services/mealItemIdentity.ts').
rel('src/server/services/mealRecommendationModel.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/userPreferences.ts',depends_on,'src/server/db.ts').
rel('src/server/services/userPreferences.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/mealRecommendation.ts',depends_on,'src/server/db.ts').
rel('src/server/services/mealRecommendation.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/mealRecommendation.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/mealRecommendation.ts',depends_on,'src/server/services/mealRecommendationAi.ts').
rel('src/server/services/mealRecommendation.ts',depends_on,'src/server/services/mealFeatures.ts').
rel('src/server/services/mealRecommendation.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('src/server/services/mealRecommendation.ts',depends_on,'src/server/services/mealItemIdentity.ts').
rel('src/server/services/mealRecommendation.ts',depends_on,'src/server/services/userPreferences.ts').
rel('src/server/services/mealRecommendationExplore.ts',depends_on,'src/server/db.ts').
rel('src/server/services/mealRecommendationExplore.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/mealRecommendationExplore.ts',depends_on,'src/server/services/seededRng.ts').
rel('src/server/services/mealRecommendationExplore.ts',depends_on,'src/server/services/mealFeatures.ts').
rel('src/server/services/mealRecommendationExplore.ts',depends_on,'src/server/services/mealRecommendation.ts').
rel('src/server/services/mealRecommendationExplore.ts',depends_on,'src/server/services/userPreferences.ts').
rel('src/server/services/mealRecommendationPreVote.ts',depends_on,'src/server/db.ts').
rel('src/server/services/mealRecommendationPreVote.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/mealRecommendationPreVote.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/mealRecommendationPreVote.ts',depends_on,'src/server/services/mealRecommendation.ts').
rel('src/server/services/mealRecommendationPreVote.ts',depends_on,'src/server/services/mealFeatures.ts').
rel('src/server/services/mealRecommendationPreVote.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('src/server/services/mealRecommendationPreVote.ts',depends_on,'src/server/services/mealItemIdentity.ts').
rel('src/server/services/mealAnticipatedLikes.ts',depends_on,'src/server/db.ts').
rel('src/server/services/mealAnticipatedLikes.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/mealAnticipatedLikes.ts',depends_on,'src/server/services/mealFeatures.ts').
rel('src/server/services/mealAnticipatedLikes.ts',depends_on,'src/server/services/mealItemIdentity.ts').
rel('src/server/services/mealAnticipatedLikes.ts',depends_on,'src/lib/types.ts').
rel('src/server/routes/foodSelections.ts',depends_on,'src/server/services/foodSelection.ts').
rel('src/server/routes/foodSelections.ts',depends_on,'src/server/services/poll.ts').
rel('src/server/routes/foodSelections.ts',depends_on,'src/server/services/mealRecommendation.ts').
rel('src/server/routes/foodSelections.ts',depends_on,'src/server/services/mealRecommendationExplore.ts').
rel('src/server/routes/foodSelections.ts',depends_on,'src/server/services/mealRecommendationPreVote.ts').
rel('src/server/routes/foodSelections.ts',depends_on,'src/server/services/mealAnticipatedLikes.ts').
rel('src/server/routes/foodSelections.ts',depends_on,'src/server/db.ts').
rel('src/server/routes/foodSelections.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/routes/foodSelections.ts',depends_on,'src/server/services/authAccess.ts').
rel('src/server/routes/foodSelections.ts',depends_on,'src/server/services/officeContext.ts').
rel('src/server/routes/foodSelections.ts',depends_on,'src/server/routes/authIdentity.ts').
rel('src/server/routes/foodSelections.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/mealRecommendationEval.ts',depends_on,'src/server/db.ts').
rel('src/server/services/mealRecommendationEval.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/mealRecommendationEval.ts',depends_on,'src/server/services/mealFeatures.ts').
rel('src/server/services/mealRecommendationEval.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('src/server/services/mealRecommendationEval.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/officeRecommenderSettings.ts',depends_on,'src/server/db.ts').
rel('src/server/services/officeRecommenderSettings.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/officeRecommenderSettings.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/officeRecommenderSettings.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('src/server/routes/recommenderAdmin.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/routes/recommenderAdmin.ts',depends_on,'src/server/routes/authIdentity.ts').
rel('src/server/routes/recommenderAdmin.ts',depends_on,'src/server/services/mealRecommendationEval.ts').
rel('src/server/routes/recommenderAdmin.ts',depends_on,'src/server/services/officeRecommenderSettings.ts').
rel('src/server/routes/recommenderAdmin.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('src/server/routes/recommenderAdmin.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/entraOidc.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/localLoginProtection.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/dbConnectivity.ts',depends_on,'src/server/db.ts').
rel('src/server/routes/auth.ts',depends_on,'src/lib/types.ts').
rel('src/server/routes/auth.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/routes/auth.ts',depends_on,'src/server/services/authSession.ts').
rel('src/server/routes/auth.ts',depends_on,'src/server/services/localAuth.ts').
rel('src/server/routes/auth.ts',depends_on,'src/server/services/entraOidc.ts').
rel('src/server/routes/auth.ts',depends_on,'src/server/services/localLoginProtection.ts').
rel('src/server/routes/auth.ts',depends_on,'src/server/services/authAccess.ts').
rel('src/server/routes/auth.ts',depends_on,'src/server/sse.ts').
rel('src/server/routes/auth.ts',depends_on,'src/server/services/officeLocation.ts').
rel('src/server/routes/auth.ts',depends_on,'src/server/services/authAudit.ts').
rel('src/server/routes/auth.ts',depends_on,'src/server/services/authAvatar.ts').
rel('src/server/routes/auth.ts',depends_on,'src/server/services/dbConnectivity.ts').
rel('src/server/services/userMenuDefaults.ts',depends_on,'src/server/db.ts').
rel('src/server/services/userMenuDefaults.ts',depends_on,'src/lib/types.ts').
rel('src/server/routes/userPreferences.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/routes/userPreferences.ts',depends_on,'src/server/services/userPreferences.ts').
rel('src/server/routes/userPreferences.ts',depends_on,'src/server/services/userMenuDefaults.ts').
rel('src/server/routes/userPreferences.ts',depends_on,'src/server/routes/authIdentity.ts').
rel('src/server/routes/userPreferences.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/shoppingList.ts',depends_on,'src/server/db.ts').
rel('src/server/services/shoppingList.ts',depends_on,'src/server/sse.ts').
rel('src/server/services/shoppingList.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/shoppingList.ts',depends_on,'src/server/services/officeLocation.ts').
rel('src/server/routes/shoppingList.ts',depends_on,'src/server/services/shoppingList.ts').
rel('src/server/routes/shoppingList.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/routes/shoppingList.ts',depends_on,'src/server/services/officeContext.ts').
rel('src/server/routes/shoppingList.ts',depends_on,'src/server/routes/authIdentity.ts').
rel('src/server/routes/shoppingList.ts',depends_on,'src/lib/types.ts').
rel('src/server/services/officePollSchedule.ts',depends_on,'src/server/db.ts').
rel('src/server/services/officePollSchedule.ts',depends_on,'src/server/services/officeLocation.ts').
rel('src/server/services/officePollSchedule.ts',depends_on,'src/server/services/pollCreation.ts').
rel('src/server/services/officePollSchedule.ts',depends_on,'src/lib/types.ts').
rel('src/server/index.ts',depends_on,'src/server/sse.ts').
rel('src/server/index.ts',depends_on,'src/server/routes/menus.ts').
rel('src/server/index.ts',depends_on,'src/server/routes/polls.ts').
rel('src/server/index.ts',depends_on,'src/server/routes/foodSelections.ts').
rel('src/server/index.ts',depends_on,'src/server/routes/recommenderAdmin.ts').
rel('src/server/index.ts',depends_on,'src/server/routes/auth.ts').
rel('src/server/index.ts',depends_on,'src/server/routes/userPreferences.ts').
rel('src/server/index.ts',depends_on,'src/server/routes/shoppingList.ts').
rel('src/server/index.ts',depends_on,'src/server/services/dbConnectivity.ts').
rel('src/server/index.ts',depends_on,'src/server/services/officePollSchedule.ts').
rel('src/server/index.ts',depends_on,'src/server/services/officeContext.ts').
rel('src/server/index.ts',depends_on,'src/server/buildInfo.ts').
rel('src/server/index.ts',depends_on,'src/server/routes/authIdentity.ts').
rel('src/server/index.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('src/server/services/mealRecommendationModelXlearn.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('src/server/services/mealRecommendationModelXlearn.ts',depends_on,'src/server/types/wlearn-xlearn.d.ts').
rel('src/client/context/AdminOfficeContext.tsx',depends_on,'src/client/config.ts').
rel('src/client/components/ui/IconButton.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/components/ui/Menu.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/components/ThemeToggle.tsx',depends_on,'src/client/context/ThemeContext.tsx').
rel('src/client/components/ThemeToggle.tsx',depends_on,'src/client/components/ui/IconButton.tsx').
rel('src/client/components/ThemeToggle.tsx',depends_on,'src/client/components/ui/Menu.tsx').
rel('src/client/components/ThemeToggle.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/components/Header.tsx',depends_on,'src/client/context/AdminOfficeContext.tsx').
rel('src/client/components/Header.tsx',depends_on,'src/client/components/ThemeToggle.tsx').
rel('src/client/components/Header.tsx',depends_on,'src/client/components/ui/IconButton.tsx').
rel('src/client/components/Header.tsx',depends_on,'src/client/components/ui/Menu.tsx').
rel('src/client/components/Header.tsx',depends_on,'src/client/vite-env.d.ts').
rel('src/client/components/Header.tsx',depends_on,'src/client/config.ts').
rel('src/client/components/Header.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/ui/Modal.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/components/DatabaseConnectionModal.tsx',depends_on,'src/client/components/ui/Modal.tsx').
rel('src/client/components/OrdersRail.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/OrdersRail.tsx',depends_on,'src/client/hooks/useCountdown.ts').
rel('src/client/components/FoodSelectionCompletedView.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/components/FoodSelectionCompletedView.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/FoodSelectionCompletedView.tsx',depends_on,'src/client/auth.ts').
rel('src/client/components/FoodSelectionCompletedView.tsx',depends_on,'src/client/api.ts').
rel('src/client/components/FoodSelectionCompletedView.tsx',depends_on,'src/client/utils/orderCopy.ts').
rel('src/client/components/FoodSelectionCompletedView.tsx',depends_on,'src/client/components/OrderCopyStatus.tsx').
rel('src/client/components/PollFinishedView.tsx',depends_on,'src/client/api.ts').
rel('src/client/components/PollFinishedView.tsx',depends_on,'src/client/components/MinutesActionDropdown.tsx').
rel('src/client/components/PollFinishedView.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/components/PollFinishedView.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/PollIdleView.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/PollIdleView.tsx',depends_on,'src/client/api.ts').
rel('src/client/components/PollIdleView.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/components/PollIdleView.tsx',depends_on,'src/client/auth.ts').
rel('src/client/components/PollIdleView.tsx',depends_on,'src/client/utils/dashboard.ts').
rel('src/client/components/PollActiveView.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/components/PollActiveView.tsx',depends_on,'src/client/hooks/useCountdown.ts').
rel('src/client/components/PollActiveView.tsx',depends_on,'src/client/api.ts').
rel('src/client/components/PollActiveView.tsx',depends_on,'src/client/components/TimerActionHeader.tsx').
rel('src/client/components/PollActiveView.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/PollActiveView.tsx',depends_on,'src/client/auth.ts').
rel('src/client/components/PollTiedView.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/components/PollTiedView.tsx',depends_on,'src/client/api.ts').
rel('src/client/components/PollTiedView.tsx',depends_on,'src/client/auth.ts').
rel('src/client/components/PollTiedView.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/MealOnboardingDialog.tsx',depends_on,'src/client/components/ui/Modal.tsx').
rel('src/client/components/MealOnboardingDialog.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/FoodSelectionActiveView.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/components/FoodSelectionActiveView.tsx',depends_on,'src/client/hooks/useCountdown.ts').
rel('src/client/components/FoodSelectionActiveView.tsx',depends_on,'src/client/api.ts').
rel('src/client/components/FoodSelectionActiveView.tsx',depends_on,'src/client/components/TimerActionHeader.tsx').
rel('src/client/components/FoodSelectionActiveView.tsx',depends_on,'src/client/components/MealOnboardingDialog.tsx').
rel('src/client/components/FoodSelectionActiveView.tsx',depends_on,'src/client/utils/orderCopy.ts').
rel('src/client/components/FoodSelectionActiveView.tsx',depends_on,'src/client/auth.ts').
rel('src/client/components/FoodSelectionActiveView.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/FoodSelectionOrderBoard.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/FoodSelectionOrderBoard.tsx',depends_on,'src/client/utils/orderCopy.ts').
rel('src/client/components/FoodSelectionOvertimeView.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/components/FoodSelectionOvertimeView.tsx',depends_on,'src/client/api.ts').
rel('src/client/components/FoodSelectionOvertimeView.tsx',depends_on,'src/client/auth.ts').
rel('src/client/components/FoodSelectionOvertimeView.tsx',depends_on,'src/client/components/FoodSelectionAbortControl.tsx').
rel('src/client/components/FoodSelectionOvertimeView.tsx',depends_on,'src/client/components/FoodSelectionOrderBoard.tsx').
rel('src/client/components/FoodSelectionOvertimeView.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/FoodSelectionOrderingView.tsx',depends_on,'src/client/api.ts').
rel('src/client/components/FoodSelectionOrderingView.tsx',depends_on,'src/client/auth.ts').
rel('src/client/components/FoodSelectionOrderingView.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/components/FoodSelectionOrderingView.tsx',depends_on,'src/client/components/FoodSelectionAbortControl.tsx').
rel('src/client/components/FoodSelectionOrderingView.tsx',depends_on,'src/client/components/FoodSelectionOrderBoard.tsx').
rel('src/client/components/FoodSelectionOrderingView.tsx',depends_on,'src/client/components/MinutesActionDropdown.tsx').
rel('src/client/components/FoodSelectionOrderingView.tsx',depends_on,'src/client/utils/orderCopy.ts').
rel('src/client/components/FoodSelectionOrderingView.tsx',depends_on,'src/client/components/OrderCopyStatus.tsx').
rel('src/client/components/FoodSelectionOrderingView.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/FoodDeliveryView.tsx',depends_on,'src/client/api.ts').
rel('src/client/components/FoodDeliveryView.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/components/FoodDeliveryView.tsx',depends_on,'src/client/hooks/useCountdown.ts').
rel('src/client/components/FoodDeliveryView.tsx',depends_on,'src/client/components/TimerActionHeader.tsx').
rel('src/client/components/FoodDeliveryView.tsx',depends_on,'src/client/utils/orderCopy.ts').
rel('src/client/components/FoodDeliveryView.tsx',depends_on,'src/client/auth.ts').
rel('src/client/components/FoodDeliveryView.tsx',depends_on,'src/client/components/OrderCopyStatus.tsx').
rel('src/client/components/FoodDeliveryView.tsx',depends_on,'src/lib/types.ts').
rel('src/client/pages/MainView.tsx',depends_on,'src/lib/types.ts').
rel('src/client/pages/MainView.tsx',depends_on,'src/client/components/NoMenusView.tsx').
rel('src/client/pages/MainView.tsx',depends_on,'src/client/components/PollIdleView.tsx').
rel('src/client/pages/MainView.tsx',depends_on,'src/client/components/PollActiveView.tsx').
rel('src/client/pages/MainView.tsx',depends_on,'src/client/components/PollTiedView.tsx').
rel('src/client/pages/MainView.tsx',depends_on,'src/client/components/PollFinishedView.tsx').
rel('src/client/pages/MainView.tsx',depends_on,'src/client/components/FoodSelectionActiveView.tsx').
rel('src/client/pages/MainView.tsx',depends_on,'src/client/components/FoodSelectionOvertimeView.tsx').
rel('src/client/pages/MainView.tsx',depends_on,'src/client/components/FoodSelectionOrderingView.tsx').
rel('src/client/pages/MainView.tsx',depends_on,'src/client/components/FoodDeliveryView.tsx').
rel('src/client/pages/MainView.tsx',depends_on,'src/client/components/FoodSelectionCompletedView.tsx').
rel('src/client/pages/ManageMenus.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/pages/ManageMenus.tsx',depends_on,'src/client/auth.ts').
rel('src/client/pages/ManageMenus.tsx',depends_on,'src/client/api.ts').
rel('src/client/pages/ManageMenus.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/ui/Input.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/components/ui/Button.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/pages/ShoppingList.tsx',depends_on,'src/client/api.ts').
rel('src/client/pages/ShoppingList.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/pages/ShoppingList.tsx',depends_on,'src/client/auth.ts').
rel('src/client/pages/ShoppingList.tsx',depends_on,'src/client/components/ui/Input.tsx').
rel('src/client/pages/ShoppingList.tsx',depends_on,'src/client/components/ui/Button.tsx').
rel('src/client/pages/ShoppingList.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/ui/Section.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/components/ui/Select.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/pages/Settings.tsx',depends_on,'src/client/context/AdminOfficeContext.tsx').
rel('src/client/pages/Settings.tsx',depends_on,'src/client/config.ts').
rel('src/client/pages/Settings.tsx',depends_on,'src/client/components/ui/Section.tsx').
rel('src/client/pages/Settings.tsx',depends_on,'src/client/components/ui/Input.tsx').
rel('src/client/pages/Settings.tsx',depends_on,'src/client/components/ui/Select.tsx').
rel('src/client/pages/Settings.tsx',depends_on,'src/client/components/ui/Button.tsx').
rel('src/client/pages/Settings.tsx',depends_on,'src/client/api.ts').
rel('src/client/pages/Settings.tsx',depends_on,'src/lib/types.ts').
rel('src/client/pages/Settings.tsx',depends_on,'src/lib/ingredientVocabulary.ts').
rel('src/client/pages/Settings.tsx',depends_on,'src/client/auth.ts').
rel('src/client/components/RecommenderAdminPanel.tsx',depends_on,'src/client/components/ui/Section.tsx').
rel('src/client/components/RecommenderAdminPanel.tsx',depends_on,'src/client/components/ui/Button.tsx').
rel('src/client/components/RecommenderAdminPanel.tsx',depends_on,'src/client/api.ts').
rel('src/client/components/RecommenderAdminPanel.tsx',depends_on,'src/lib/types.ts').
rel('src/client/pages/Administration.tsx',depends_on,'src/client/auth.ts').
rel('src/client/pages/Administration.tsx',depends_on,'src/client/components/RecommenderAdminPanel.tsx').
rel('src/client/pages/Administration.tsx',depends_on,'src/client/config.ts').
rel('src/client/pages/Administration.tsx',depends_on,'src/client/context/AdminOfficeContext.tsx').
rel('src/client/pages/Administration.tsx',depends_on,'src/lib/types.ts').
rel('src/client/App.tsx',depends_on,'src/client/components/Header.tsx').
rel('src/client/App.tsx',depends_on,'src/client/components/DatabaseConnectionModal.tsx').
rel('src/client/App.tsx',depends_on,'src/client/components/OrdersRail.tsx').
rel('src/client/App.tsx',depends_on,'src/client/components/FoodSelectionCompletedView.tsx').
rel('src/client/App.tsx',depends_on,'src/client/components/PollFinishedView.tsx').
rel('src/client/App.tsx',depends_on,'src/client/pages/MainView.tsx').
rel('src/client/App.tsx',depends_on,'src/client/pages/ManageMenus.tsx').
rel('src/client/App.tsx',depends_on,'src/client/pages/ShoppingList.tsx').
rel('src/client/App.tsx',depends_on,'src/client/pages/Settings.tsx').
rel('src/client/App.tsx',depends_on,'src/client/pages/Administration.tsx').
rel('src/client/App.tsx',depends_on,'src/client/api.ts').
rel('src/client/App.tsx',depends_on,'src/lib/types.ts').
rel('src/client/App.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/App.tsx',depends_on,'src/client/context/AdminOfficeContext.tsx').
rel('src/client/App.tsx',depends_on,'src/client/hooks/useSSE.ts').
rel('src/client/App.tsx',depends_on,'src/client/hooks/useAppPhase.ts').
rel('src/client/App.tsx',depends_on,'src/client/hooks/usePhaseNotifications.ts').
rel('src/client/App.tsx',depends_on,'src/client/hooks/useNotificationPreference.ts').
rel('src/client/App.tsx',depends_on,'src/client/auth.ts').
rel('src/client/App.tsx',depends_on,'src/client/config.ts').
rel('src/client/App.tsx',depends_on,'src/client/vite-env.d.ts').
rel('src/client/components/ui/Card.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/components/ui/Panel.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/components/AuthGate.tsx',depends_on,'src/client/config.ts').
rel('src/client/components/AuthGate.tsx',depends_on,'src/client/context/AdminOfficeContext.tsx').
rel('src/client/components/AuthGate.tsx',depends_on,'src/client/components/ui/Button.tsx').
rel('src/client/components/AuthGate.tsx',depends_on,'src/client/components/ui/Card.tsx').
rel('src/client/components/AuthGate.tsx',depends_on,'src/client/components/ui/Input.tsx').
rel('src/client/components/AuthGate.tsx',depends_on,'src/client/components/ui/Panel.tsx').
rel('src/client/components/AuthGate.tsx',depends_on,'src/lib/types.ts').
rel('src/client/components/AuthGate.tsx',depends_on,'src/client/auth.ts').
rel('src/client/main.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('src/client/main.tsx',depends_on,'src/client/context/ThemeContext.tsx').
rel('src/client/main.tsx',depends_on,'src/client/App.tsx').
rel('src/client/main.tsx',depends_on,'src/client/components/AuthGate.tsx').
rel('src/client/main.tsx',depends_on,'src/client/auth.ts').
rel('src/client/components/ui/Badge.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/components/ui/Divider.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/components/ui/FormField.tsx',depends_on,'src/client/lib/cn.ts').
rel('src/client/components/ui/Textarea.tsx',depends_on,'src/client/lib/cn.ts').
rel('tests/client/app-context.test.ts',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/app-context.test.ts',depends_on,'src/lib/types.ts').
rel('tests/client/helpers.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/dashboard-utils.test.ts',depends_on,'tests/client/helpers.tsx').
rel('tests/client/dashboard-utils.test.ts',depends_on,'src/client/utils/dashboard.ts').
rel('tests/client/useAppPhase.test.ts',depends_on,'src/client/hooks/useAppPhase.ts').
rel('tests/client/useAppPhase.test.ts',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/useAppPhase.test.ts',depends_on,'src/lib/types.ts').
rel('tests/client/usePhaseNotifications.test.ts',depends_on,'src/lib/types.ts').
rel('tests/client/usePhaseNotifications.test.ts',depends_on,'src/client/hooks/usePhaseNotifications.ts').
rel('tests/client/useSSE.test.ts',depends_on,'src/client/hooks/useSSE.ts').
rel('tests/client/useSSE.test.ts',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/useSSE.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/auth-approval-gate.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/auth-approval-gate.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/helpers/db.ts',depends_on,'src/server/db.ts').
rel('tests/server/helpers/db.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('tests/server/auth-approval-reminder.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/auth-approval-reminder.test.ts',depends_on,'src/server/services/authAccess.ts').
rel('tests/server/auth-approval-reminder.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/auth-approval-reminder.test.ts',depends_on,'src/server/services/notificationEmail.ts').
rel('tests/server/auth-approval-reminder.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/auth-audit.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/auth-audit.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/auth-audit.test.ts',depends_on,'src/server/services/authAccess.ts').
rel('tests/server/auth-audit.test.ts',depends_on,'src/server/services/localAuth.ts').
rel('tests/server/auth-audit.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/auth-audit.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/auth-audit.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/auth-avatar.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/auth-avatar.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/auth-avatar.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/auth-avatar.test.ts',depends_on,'src/server/services/authAvatar.ts').
rel('tests/server/auth-avatar.test.ts',depends_on,'src/server/services/localAuth.ts').
rel('tests/server/auth-avatar.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/auth-hardening.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/auth-hardening.test.ts',depends_on,'src/server/services/localAuth.ts').
rel('tests/server/auth-hardening.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/auth-hardening.test.ts',depends_on,'src/server/services/entraOidc.ts').
rel('tests/server/auth-hardening.test.ts',depends_on,'src/server/services/localLoginProtection.ts').
rel('tests/server/auth-hardening.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/auth-hardening.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/auth-routes-config.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/auth-routes-config.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/auth-routes-config.test.ts',depends_on,'src/server/services/dbConnectivity.ts').
rel('tests/server/auth-session.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/authenticated-get-routes.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/authenticated-get-routes.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/base-path.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/db-connectivity.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/db-connectivity.test.ts',depends_on,'src/server/services/dbConnectivity.ts').
rel('tests/server/display-name-identity.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/display-name-identity.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/display-name-identity.test.ts',depends_on,'src/server/services/authAccess.ts').
rel('tests/server/display-name-identity.test.ts',depends_on,'src/server/services/displayName.ts').
rel('tests/server/display-name-identity.test.ts',depends_on,'src/server/services/localAuth.ts').
rel('tests/server/display-name-identity.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/display-name-identity.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/display-name-identity.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/display-name-identity.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/food-order-rating-export.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/food-order-rating-export.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/food-order-rating-export.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/food-order-rating-export.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/food-order-rating-export.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/food-order-rating-export.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/food-order-rating-export.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/food-order-rating-export.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/food-order-rating-export.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/food-selection-authz.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/food-selection-authz.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/food-selection-authz.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/food-selection-authz.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/food-selection-authz.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/food-selection-authz.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/food-selection-authz.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/food-selection-authz.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/food-selection-authz.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/food-selection-reminder.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/food-selection-reminder.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/food-selection-reminder.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/food-selection-reminder.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/food-selection-reminder.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/food-selection-reminder.test.ts',depends_on,'src/server/sse.ts').
rel('tests/server/food-selection-reminder.test.ts',depends_on,'src/server/services/userMenuDefaults.ts').
rel('tests/server/food-selection-reminder.test.ts',depends_on,'src/server/services/notificationEmail.ts').
rel('tests/server/food-selection-reminder.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/food-selection-routes.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/food-selection-routes.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/food-selection-routes.test.ts',depends_on,'src/server/services/pollCreation.ts').
rel('tests/server/food-selection-routes.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/food-selection-routes.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/food-selection-routes.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/food-selection-routes.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/food-selection-routes.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/food-selection-routes.test.ts',depends_on,'src/server/services/userMenuDefaults.ts').
rel('tests/server/food-selection-routes.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/food-selection-service.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/food-selection-service.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/food-selection-service.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/food-selection-service.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/food-selection-service.test.ts',depends_on,'src/server/services/userMenuDefaults.ts').
rel('tests/server/food-selection-service.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/food-selection-service.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/food-selection-service.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/food-selection-service.test.ts',depends_on,'src/server/sse.ts').
rel('tests/server/food-selection-timer.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/food-selection-timer.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/food-selection-timer.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/food-selection-timer.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/food-selection-timer.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/food-selection-timer.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/local-auth.test.ts',depends_on,'src/server/services/localAuth.ts').
rel('tests/server/local-user-management-authz.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/local-user-management-authz.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/local-user-management-authz.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/meal-anticipated-likes.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/meal-anticipated-likes.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/meal-anticipated-likes.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/meal-anticipated-likes.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/meal-anticipated-likes.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/meal-anticipated-likes.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/meal-anticipated-likes.test.ts',depends_on,'src/server/services/mealRecommendation.ts').
rel('tests/server/meal-anticipated-likes.test.ts',depends_on,'src/server/services/mealAnticipatedLikes.ts').
rel('tests/server/meal-anticipated-likes.test.ts',depends_on,'src/server/services/mealItemIdentity.ts').
rel('tests/server/meal-anticipated-likes.test.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('tests/server/meal-anticipated-likes.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/meal-features-persistence.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/meal-features-persistence.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/meal-features-persistence.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/meal-features-persistence.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/meal-features-persistence.test.ts',depends_on,'src/server/services/mealFeatures.ts').
rel('tests/server/meal-features-persistence.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/meal-features-tagging.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/meal-features-tagging.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/meal-features-tagging.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/meal-features-tagging.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/meal-features-tagging.test.ts',depends_on,'src/server/services/mealRecommendationAi.ts').
rel('tests/server/meal-features-tagging.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/meal-features.test.ts',depends_on,'src/server/services/mealFeatures.ts').
rel('tests/server/meal-item-identity.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/meal-item-identity.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/meal-item-identity.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/meal-item-identity.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/meal-item-identity.test.ts',depends_on,'src/server/services/mealItemIdentity.ts').
rel('tests/server/meal-item-identity.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/meal-recommendation-ai.test.ts',depends_on,'src/server/services/mealRecommendationAi.ts').
rel('tests/server/meal-recommendation-eval.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/meal-recommendation-eval.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/meal-recommendation-eval.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/meal-recommendation-eval.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/meal-recommendation-eval.test.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('tests/server/meal-recommendation-eval.test.ts',depends_on,'src/server/services/mealRecommendationEval.ts').
rel('tests/server/meal-recommendation-eval.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/meal-recommendation-explore.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/meal-recommendation-explore.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/meal-recommendation-explore.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/meal-recommendation-explore.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/meal-recommendation-explore.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/meal-recommendation-explore.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/meal-recommendation-explore.test.ts',depends_on,'src/server/services/mealRecommendation.ts').
rel('tests/server/meal-recommendation-explore.test.ts',depends_on,'src/server/services/mealRecommendationExplore.ts').
rel('tests/server/meal-recommendation-explore.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/meal-recommendation-model-xlearn.test.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('tests/server/meal-recommendation-model-xlearn.test.ts',depends_on,'src/server/services/mealRecommendationModelXlearn.ts').
rel('tests/server/meal-recommendation-model.test.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('tests/server/meal-recommendation-pre-vote.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/meal-recommendation-pre-vote.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/meal-recommendation-pre-vote.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/meal-recommendation-pre-vote.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/meal-recommendation-pre-vote.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/meal-recommendation-pre-vote.test.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('tests/server/meal-recommendation-pre-vote.test.ts',depends_on,'src/server/services/mealRecommendationPreVote.ts').
rel('tests/server/meal-recommendation-pre-vote.test.ts',depends_on,'src/server/services/mealRecommendation.ts').
rel('tests/server/meal-recommendation-pre-vote.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/meal-recommendation-routes.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/meal-recommendation-routes.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/meal-recommendation-routes.test.ts',depends_on,'src/server/services/pollCreation.ts').
rel('tests/server/meal-recommendation-routes.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/meal-recommendation-routes.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/meal-recommendation-routes.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/meal-recommendation-routes.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/meal-recommendation-routes.test.ts',depends_on,'src/server/services/mealRecommendationAi.ts').
rel('tests/server/meal-recommendation-routes.test.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('tests/server/meal-recommendation-routes.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/meal-recommendation-routes.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'src/server/services/userPreferences.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'src/server/services/userMenuDefaults.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'src/server/services/mealRecommendation.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'src/server/services/mealFeatures.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'src/server/services/mealItemIdentity.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/meal-recommendation-service.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/meal-recommendation-transfer.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/meal-recommendation-transfer.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/meal-recommendation-transfer.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/meal-recommendation-transfer.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/meal-recommendation-transfer.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/meal-recommendation-transfer.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/meal-recommendation-transfer.test.ts',depends_on,'src/server/services/mealRecommendation.ts').
rel('tests/server/meal-recommendation-transfer.test.ts',depends_on,'src/server/services/mealItemIdentity.ts').
rel('tests/server/meal-recommendation-transfer.test.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('tests/server/meal-recommendation-transfer.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/menu-routes.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/menu-routes.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/menu-routes.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/menu-routes.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/menu-routes.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/menu-routes.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/menu-service.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/menu-service.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/menu-service.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/menu-service.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/notification-email.test.ts',depends_on,'src/server/services/notificationEmail.ts').
rel('tests/server/office-location-service.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/office-location-service.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/office-location-service.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/office-location-service.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/office-poll-schedule.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/office-poll-schedule.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/office-poll-schedule.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/office-poll-schedule.test.ts',depends_on,'src/server/services/officePollSchedule.ts').
rel('tests/server/poll-authz.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/poll-authz.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/poll-authz.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/poll-authz.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/poll-authz.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/poll-authz.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/poll-authz.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/poll-authz.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/poll-routes.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/poll-routes.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/poll-routes.test.ts',depends_on,'src/server/services/pollCreation.ts').
rel('tests/server/poll-routes.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/poll-routes.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/poll-routes.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/poll-routes.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/poll-routes.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/poll-service.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/poll-service.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/poll-service.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/poll-service.test.ts',depends_on,'src/server/services/authAccess.ts').
rel('tests/server/poll-service.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/poll-service.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/poll-service.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/poll-service.test.ts',depends_on,'src/server/services/notificationEmail.ts').
rel('tests/server/poll-service.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/poll-timer.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/poll-timer.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/poll-timer.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/poll-timer.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/poll-timer.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/recommender-admin-routes.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/recommender-admin-routes.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/recommender-admin-routes.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/recommender-admin-routes.test.ts',depends_on,'src/server/services/mealRecommendationModel.ts').
rel('tests/server/recommender-admin-routes.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/recommender-admin-routes.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/recommender-admin-routes.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/recommender-admin-routes.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/retention-integration.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/retention-integration.test.ts',depends_on,'src/server/services/pollCreation.ts').
rel('tests/server/retention-integration.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/retention-integration.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/retention-integration.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/retention-integration.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/retention-integration.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/route-utils.test.ts',depends_on,'src/server/routes/routeUtils.ts').
rel('tests/server/shopping-list-routes.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/shopping-list-routes.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/shopping-list-routes.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/shopping-list-routes.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/shopping-list-routes.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/shopping-list-routes.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/shopping-list-service.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/shopping-list-service.test.ts',depends_on,'src/server/sse.ts').
rel('tests/server/shopping-list-service.test.ts',depends_on,'src/server/services/shoppingList.ts').
rel('tests/server/shopping-list-service.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/shopping-list-service.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/sse-integration.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/sse-integration.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/sse-integration.test.ts',depends_on,'src/server/services/pollCreation.ts').
rel('tests/server/sse-integration.test.ts',depends_on,'src/server/services/poll.ts').
rel('tests/server/sse-integration.test.ts',depends_on,'src/server/services/foodSelection.ts').
rel('tests/server/sse-integration.test.ts',depends_on,'src/server/services/officeLocation.ts').
rel('tests/server/sse-integration.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/sse-integration.test.ts',depends_on,'src/server/db.ts').
rel('tests/server/sse-integration.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/sse.test.ts',depends_on,'src/server/sse.ts').
rel('tests/server/user-menu-defaults-service.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/user-menu-defaults-service.test.ts',depends_on,'src/server/services/menu.ts').
rel('tests/server/user-menu-defaults-service.test.ts',depends_on,'src/server/services/userMenuDefaults.ts').
rel('tests/server/user-menu-defaults-service.test.ts',depends_on,'src/lib/types.ts').
rel('tests/server/user-preferences-routes.test.ts',depends_on,'src/server/index.ts').
rel('tests/server/user-preferences-routes.test.ts',depends_on,'tests/server/helpers/db.ts').
rel('tests/server/user-preferences-routes.test.ts',depends_on,'src/server/services/authSession.ts').
rel('tests/server/user-preferences-routes.test.ts',depends_on,'src/server/services/localAuth.ts').
rel('tests/server/user-preferences-routes.test.ts',depends_on,'src/server/db.ts').
rel('tests/client/Administration.test.tsx',depends_on,'src/client/pages/Administration.tsx').
rel('tests/client/Administration.test.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/App.test.tsx',depends_on,'src/client/App.tsx').
rel('tests/client/App.test.tsx',depends_on,'tests/client/helpers.tsx').
rel('tests/client/App.test.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/App.test.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/AuthGate.test.tsx',depends_on,'src/client/components/AuthGate.tsx').
rel('tests/client/AuthGate.test.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/FoodDeliveryView.test.tsx',depends_on,'tests/client/helpers.tsx').
rel('tests/client/FoodDeliveryView.test.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/FoodDeliveryView.test.tsx',depends_on,'src/client/components/FoodDeliveryView.tsx').
rel('tests/client/FoodDeliveryView.test.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/FoodSelectionActiveView.test.tsx',depends_on,'tests/client/helpers.tsx').
rel('tests/client/FoodSelectionActiveView.test.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/FoodSelectionActiveView.test.tsx',depends_on,'src/client/hooks/useCountdown.ts').
rel('tests/client/FoodSelectionActiveView.test.tsx',depends_on,'src/client/components/FoodSelectionActiveView.tsx').
rel('tests/client/FoodSelectionActiveView.test.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/FoodSelectionCompletedView.test.tsx',depends_on,'tests/client/helpers.tsx').
rel('tests/client/FoodSelectionCompletedView.test.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/FoodSelectionCompletedView.test.tsx',depends_on,'src/client/api.ts').
rel('tests/client/FoodSelectionCompletedView.test.tsx',depends_on,'src/client/components/FoodSelectionCompletedView.tsx').
rel('tests/client/FoodSelectionOrderingView.test.tsx',depends_on,'tests/client/helpers.tsx').
rel('tests/client/FoodSelectionOrderingView.test.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/FoodSelectionOrderingView.test.tsx',depends_on,'src/client/components/FoodSelectionOrderingView.tsx').
rel('tests/client/FoodSelectionOvertimeView.test.tsx',depends_on,'tests/client/helpers.tsx').
rel('tests/client/FoodSelectionOvertimeView.test.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/FoodSelectionOvertimeView.test.tsx',depends_on,'src/client/components/FoodSelectionOvertimeView.tsx').
rel('tests/client/Header.test.tsx',depends_on,'src/client/components/Header.tsx').
rel('tests/client/Header.test.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/MainView.test.tsx',depends_on,'src/client/pages/MainView.tsx').
rel('tests/client/MainView.test.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/ManageMenus.test.tsx',depends_on,'tests/client/helpers.tsx').
rel('tests/client/ManageMenus.test.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/ManageMenus.test.tsx',depends_on,'src/client/pages/ManageMenus.tsx').
rel('tests/client/MealOnboardingDialog.test.tsx',depends_on,'src/client/components/MealOnboardingDialog.tsx').
rel('tests/client/MealOnboardingDialog.test.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/NoMenusView.test.tsx',depends_on,'src/client/components/NoMenusView.tsx').
rel('tests/client/OrdersRail.test.tsx',depends_on,'src/client/components/OrdersRail.tsx').
rel('tests/client/OrdersRail.test.tsx',depends_on,'tests/client/helpers.tsx').
rel('tests/client/PollActiveView.test.tsx',depends_on,'tests/client/helpers.tsx').
rel('tests/client/PollActiveView.test.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/PollActiveView.test.tsx',depends_on,'src/client/hooks/useCountdown.ts').
rel('tests/client/PollActiveView.test.tsx',depends_on,'src/client/components/PollActiveView.tsx').
rel('tests/client/PollActiveView.test.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/PollFinishedView.test.tsx',depends_on,'tests/client/helpers.tsx').
rel('tests/client/PollFinishedView.test.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/PollFinishedView.test.tsx',depends_on,'src/client/components/PollFinishedView.tsx').
rel('tests/client/PollFinishedView.test.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/PollIdleView.test.tsx',depends_on,'tests/client/helpers.tsx').
rel('tests/client/PollIdleView.test.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/PollIdleView.test.tsx',depends_on,'src/client/components/PollIdleView.tsx').
rel('tests/client/PollTiedView.test.tsx',depends_on,'tests/client/helpers.tsx').
rel('tests/client/PollTiedView.test.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/PollTiedView.test.tsx',depends_on,'src/client/components/PollTiedView.tsx').
rel('tests/client/PollTiedView.test.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/RecommenderAdminPanel.test.tsx',depends_on,'src/client/components/RecommenderAdminPanel.tsx').
rel('tests/client/Settings.test.tsx',depends_on,'src/client/pages/Settings.tsx').
rel('tests/client/ShoppingList.test.tsx',depends_on,'src/client/context/AppContext.tsx').
rel('tests/client/ShoppingList.test.tsx',depends_on,'src/client/pages/ShoppingList.tsx').
rel('tests/client/ShoppingList.test.tsx',depends_on,'src/lib/types.ts').
rel('tests/client/ThemeContext.test.tsx',depends_on,'src/client/context/ThemeContext.tsx').
entity(db,module).
entity(mealRecommendation,service).
entity(mealRecommendationModel,service).
entity(mealRecommendationAi,service).
entity(mealRecommendationEval,service).
entity(mealFeatures,service).
entity(mealItemIdentity,service).
entity(officeRecommenderSettings,service).
entity(userPreferences,service).
entity(lib_types,module).
entity(routeUtils,module).
entity(recommenderAdmin,route).
entity('POST:/api/menus',endpoint).
prop('POST:/api/menus',method,post).
prop('POST:/api/menus',mutates_state,true).
entity('POST:/api/menus/import',endpoint).
prop('POST:/api/menus/import',method,post).
prop('POST:/api/menus/import',mutates_state,true).
entity('PUT:/api/menus/:id',endpoint).
prop('PUT:/api/menus/:id',method,put).
prop('PUT:/api/menus/:id',path,'/api/menus/:id').
prop('PUT:/api/menus/:id',mutates_state,true).
entity('DELETE:/api/menus/:id',endpoint).
prop('DELETE:/api/menus/:id',method,delete).
prop('DELETE:/api/menus/:id',path,'/api/menus/:id').
prop('DELETE:/api/menus/:id',mutates_state,true).
entity('POST:/api/menus/:menuId/items',endpoint).
prop('POST:/api/menus/:menuId/items',method,post).
prop('POST:/api/menus/:menuId/items',path,'/api/menus/:menuId/items').
prop('POST:/api/menus/:menuId/items',mutates_state,true).
entity('PUT:/api/menus/:menuId/items/:id',endpoint).
prop('PUT:/api/menus/:menuId/items/:id',method,put).
prop('PUT:/api/menus/:menuId/items/:id',path,'/api/menus/:menuId/items/:id').
prop('PUT:/api/menus/:menuId/items/:id',mutates_state,true).
entity('DELETE:/api/menus/:menuId/items/:id',endpoint).
prop('DELETE:/api/menus/:menuId/items/:id',method,delete).
prop('DELETE:/api/menus/:menuId/items/:id',path,'/api/menus/:menuId/items/:id').
prop('DELETE:/api/menus/:menuId/items/:id',mutates_state,true).
entity('GET:/api/menus',endpoint).
prop('GET:/api/menus',method,get).
prop('GET:/api/menus',mutates_state,false).
entity('GET:/api/food-selections/active',endpoint).
prop('GET:/api/food-selections/active',method,get).
prop('GET:/api/food-selections/active',mutates_state,false).
entity('GET:/api/food-selections/history',endpoint).
prop('GET:/api/food-selections/history',method,get).
prop('GET:/api/food-selections/history',mutates_state,false).
entity('GET:/api/food-selections/:id/fallback-candidates',endpoint).
prop('GET:/api/food-selections/:id/fallback-candidates',method,get).
prop('GET:/api/food-selections/:id/fallback-candidates',path,'/api/food-selections/:id/fallback-candidates').
prop('GET:/api/food-selections/:id/fallback-candidates',mutates_state,false).
entity('GET:/api/polls/active',endpoint).
prop('GET:/api/polls/active',method,get).
prop('GET:/api/polls/active',mutates_state,false).
entity('GET:/api/polls/:id',endpoint).
prop('GET:/api/polls/:id',method,get).
prop('GET:/api/polls/:id',path,'/api/polls/:id').
prop('GET:/api/polls/:id',mutates_state,false).
entity('GET:/api/shopping-list',endpoint).
prop('GET:/api/shopping-list',method,get).
prop('GET:/api/shopping-list',mutates_state,false).
prop('POST:/api/menus',requires_auth,true).
prop('POST:/api/menus/import',requires_auth,true).
prop('PUT:/api/menus/:id',requires_auth,true).
prop('DELETE:/api/menus/:id',requires_auth,true).
prop('POST:/api/menus/:menuId/items',requires_auth,true).
prop('PUT:/api/menus/:menuId/items/:id',requires_auth,true).
prop('DELETE:/api/menus/:menuId/items/:id',requires_auth,true).
prop('GET:/api/menus',requires_auth,true).
prop('GET:/api/food-selections/active',requires_auth,true).
prop('GET:/api/food-selections/history',requires_auth,true).
prop('GET:/api/food-selections/:id/fallback-candidates',requires_auth,true).
prop('GET:/api/polls/active',requires_auth,true).
prop('GET:/api/polls/:id',requires_auth,true).
prop('GET:/api/shopping-list',requires_auth,true).
prop('GET:/api/menus',path,'/api/menus').
prop('GET:/api/shopping-list',path,'/api/shopping-list').
prop('GET:/api/food-selections/active',path,'/api/food-selections/active').
prop('GET:/api/food-selections/history',path,'/api/food-selections/history').
prop('GET:/api/polls/active',path,'/api/polls/active').
prop('POST:/api/menus/import',path,'/api/menus/import').
prop('POST:/api/menus',path,'/api/menus').
