% structure.pl — Tier 2 empirical facts, scanned from the codebase by the agent.
% Same EAV shape as axioms; the loader tags these as `observed`. Each fact should
% have a matching entry in provenance.pl.
%
% entity('/abc', endpoint).
% prop('/abc', requires_auth, true).
% rel(c42, depends_on, lib_theme).
entity(mealRecommendation,service).
entity(mealRecommendationModel,service).
entity(mealRecommendationAi,service).
entity(mealRecommendationEval,service).
entity(mealFeatures,service).
entity(mealItemIdentity,service).
entity(officeRecommenderSettings,service).
entity(userPreferences,service).
entity(db,module).
entity(lib_types,module).
entity(routeUtils,module).
entity(authIdentity,module).
entity(recommenderAdmin,route).
rel(mealRecommendation,depends_on,db).
rel(mealRecommendation,depends_on,mealRecommendationAi).
rel(mealRecommendation,depends_on,mealFeatures).
rel(mealRecommendation,depends_on,mealRecommendationModel).
rel(mealRecommendation,depends_on,mealItemIdentity).
rel(mealRecommendation,depends_on,userPreferences).
rel(mealRecommendation,depends_on,lib_types).
rel(recommenderAdmin,depends_on,routeUtils).
rel(recommenderAdmin,depends_on,authIdentity).
rel(recommenderAdmin,depends_on,mealRecommendationEval).
rel(recommenderAdmin,depends_on,officeRecommenderSettings).
rel(recommenderAdmin,depends_on,mealRecommendationModel).
rel(recommenderAdmin,depends_on,lib_types).
entity('POST:/api/menus',endpoint).
prop('POST:/api/menus',method,post).
prop('POST:/api/menus',path,'/api/menus').
prop('POST:/api/menus',mutates_state,true).
entity('POST:/api/menus/import',endpoint).
prop('POST:/api/menus/import',method,post).
prop('POST:/api/menus/import',path,'/api/menus/import').
prop('POST:/api/menus/import',mutates_state,true).
entity('PUT:/api/menus/:id',endpoint).
prop('PUT:/api/menus/:id',method,put).
prop('PUT:/api/menus/:id',path,'/api/menus/:id').
prop('PUT:/api/menus/:id',mutates_state,true).
entity('DELETE:/api/menus/:id',endpoint).
prop('DELETE:/api/menus/:id',method,delete).
prop('DELETE:/api/menus/:id',path,'/api/menus/:id').
prop('DELETE:/api/menus/:id',mutates_state,true).
entity('POST:/api/menus/:menuId/items',endpoint).
prop('POST:/api/menus/:menuId/items',method,post).
prop('POST:/api/menus/:menuId/items',path,'/api/menus/:menuId/items').
prop('POST:/api/menus/:menuId/items',mutates_state,true).
entity('PUT:/api/menus/:menuId/items/:id',endpoint).
prop('PUT:/api/menus/:menuId/items/:id',method,put).
prop('PUT:/api/menus/:menuId/items/:id',path,'/api/menus/:menuId/items/:id').
prop('PUT:/api/menus/:menuId/items/:id',mutates_state,true).
entity('DELETE:/api/menus/:menuId/items/:id',endpoint).
prop('DELETE:/api/menus/:menuId/items/:id',method,delete).
prop('DELETE:/api/menus/:menuId/items/:id',path,'/api/menus/:menuId/items/:id').
prop('DELETE:/api/menus/:menuId/items/:id',mutates_state,true).
entity('GET:/api/menus',endpoint).
prop('GET:/api/menus',method,get).
prop('GET:/api/menus',path,'/api/menus').
prop('GET:/api/menus',mutates_state,false).
entity('GET:/api/food-selections/active',endpoint).
prop('GET:/api/food-selections/active',method,get).
prop('GET:/api/food-selections/active',path,'/api/food-selections/active').
prop('GET:/api/food-selections/active',mutates_state,false).
entity('GET:/api/food-selections/history',endpoint).
prop('GET:/api/food-selections/history',method,get).
prop('GET:/api/food-selections/history',path,'/api/food-selections/history').
prop('GET:/api/food-selections/history',mutates_state,false).
entity('GET:/api/food-selections/:id/fallback-candidates',endpoint).
prop('GET:/api/food-selections/:id/fallback-candidates',method,get).
prop('GET:/api/food-selections/:id/fallback-candidates',path,'/api/food-selections/:id/fallback-candidates').
prop('GET:/api/food-selections/:id/fallback-candidates',mutates_state,false).
entity('GET:/api/polls/active',endpoint).
prop('GET:/api/polls/active',method,get).
prop('GET:/api/polls/active',path,'/api/polls/active').
prop('GET:/api/polls/active',mutates_state,false).
entity('GET:/api/polls/:id',endpoint).
prop('GET:/api/polls/:id',method,get).
prop('GET:/api/polls/:id',path,'/api/polls/:id').
prop('GET:/api/polls/:id',mutates_state,false).
entity('GET:/api/shopping-list',endpoint).
prop('GET:/api/shopping-list',method,get).
prop('GET:/api/shopping-list',path,'/api/shopping-list').
prop('GET:/api/shopping-list',mutates_state,false).
prop('POST:/api/menus',requires_auth,true).
prop('POST:/api/menus/import',requires_auth,true).
prop('PUT:/api/menus/:id',requires_auth,true).
prop('DELETE:/api/menus/:id',requires_auth,true).
prop('POST:/api/menus/:menuId/items',requires_auth,true).
prop('PUT:/api/menus/:menuId/items/:id',requires_auth,true).
prop('DELETE:/api/menus/:menuId/items/:id',requires_auth,true).
prop('GET:/api/menus',requires_auth,true).
prop('GET:/api/food-selections/active',requires_auth,true).
prop('GET:/api/food-selections/history',requires_auth,true).
prop('GET:/api/food-selections/:id/fallback-candidates',requires_auth,true).
prop('GET:/api/polls/active',requires_auth,true).
prop('GET:/api/polls/:id',requires_auth,true).
prop('GET:/api/shopping-list',requires_auth,true).
entity(faim,tool).
prop(faim,version,'0.3.0').
